### ISSUE TITLE
oauth no setup in readme

### ISSUE THREAD

**Issue by davtur19** [vlang/vorum#12]
i setup CLIENT_ID and CLIENT_SECRET but oauth_cb function is never called, in the readme it is not explained how to configure oauth

**Comment by davtur19** [comment]
I was able to understand that the callbackurl should be set to this address http://doman/oauth_cb/ 
now the code is printed in the console but the login does not work, it's like I'm never logged in
the cookie `id` is set but not the cookie `q`

now after having recreated the database it has started to work, probably an id had been set incorrectly since I was not using the path `oauth_cb/` but I used `/`

**Comment by medvednikov** [comment]
Thanks, I've updated the readme.
