### ISSUE TITLE
MacOS can not build

### ISSUE THREAD

**Issue by cheft** [vlang/vorum#4]
Mac OS 10.14.5 (18F132)

➜  vtalk git:(master) ✗ v
V 0.1.17

➜  vtalk git:(master) ✗ v .
V panic: C error. This should never happen. Please create a GitHub issue.

**Comment by medvednikov** [comment]
Can you run it with `v -debug .` ?

**Comment by sylviot** [comment]
Arch (Manjaro) 18.0.4

```shell
[sylviot vorum]$ v -debug .

.vorum.c:112:10: fatal error: libpq-fe.h: No such file or directory
 #include <libpq-fe.h>
          ^~~~~~~~~~~~
compilation terminated.
```

I'm running without PGsql installed.

**Comment by medvednikov** [comment]
you should install it

I'll release sqlite backend soon.

**Comment by sylviot** [comment]
After install postgres
```
.vorum.c:316:6: error: field ‘cur_user’ has incomplete type
 User cur_user;
      ^~~~~~~~
```

**Comment by cheft** [comment]
`
brew install postgresql
`

build ok.

**Comment by enghitalo** [comment]
So try installing libpq-dev or its equivalent for your OS:

For Ubuntu/Debian systems: `sudo apt-get install libpq-dev`
On [Red Hat Linux](http://en.wikipedia.org/wiki/Red_Hat_Linux) (RHEL) systems: `yum install postgresql-devel`
For Mac [Homebrew](https://en.wikipedia.org/wiki/Homebrew_%28package_management_software%29): `brew install postgresql`
For Mac [MacPorts](http://en.wikipedia.org/wiki/MacPorts) PostgreSQL: `gem install pg -- --with-pg-config=/opt/local/lib/postgresql[version number]/bin/pg_config`
For [OpenSuse](https://en.wikipedia.org/wiki/OpenSUSE): `zypper in postgresql-devel`
For [ArchLinux](https://en.wikipedia.org/wiki/Arch_Linux): `pacman -S postgresql-libs`
