### ISSUE TITLE
Cannot build vorum with the latest v (git master)

### ISSUE THREAD

**Issue by iredmail** [vlang/vorum#9]
With latest git versions of v and vorum:

```
$ cd vorum
$ v .
check()
next token = `$`
_user.v:11 expected `.name` but got `"
        select name from users 
        where id="`
```

**Comment by changrui** [comment]
Yes, I also get this error.

**Comment by iredmail** [comment]
Same issue with v 0.1.19.

**Comment by vbrazo** [comment]
+1

**Comment by vbrazo** [comment]
`v0.1.19`

<img width="730" alt="Screen Shot 2019-09-14 at 12 21 56 AM" src="https://user-images.githubusercontent.com/1292556/64904900-ae9c8b00-d685-11e9-9d54-c3836a48b745.png">

**Comment by medvednikov** [comment]
Fixed.
